baseURL = "https://vinsk0h.github.io/"
languageCode = "en-us"
title = "vinsk0h's safezone"
theme = "m10c"

[params]
  author = "Vincent Mauté"
  description = "A blog about all things IT/infoSec"

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/vinsk0h"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/vinsk0h"
