baseURL = 'https://vinsk0h.github.io/'
author = 'vinsk0h'
description = 'in progress'
avatar = 'D:\Pictures\Cat_fency.jpg'
menu_item_separator = '-'
favicon = ''


[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"