name: CommitWebSite
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.68.3"      - name: Build
        run: hugo --minify      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.HUGO }}
          external_repository: vinsk0h/xyz.github.io
          publish_dir: ./public
          keep_files: true
          user_name: vinsk0h
          user_email: mautevincent@gmail.com
          publish_branch: main
          cname: https://vinsk0h.github.io/